name: Deploy Azure Bicep

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log into Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Resource Group
        uses: azure/cli@v2
        with:
          inlineScript: |
            az group create --name rg-iac101-demo --location northeurope

      - name: Deploy Bicep Architecture
        uses: azure/arm-deploy@v2
        with:
          scope: resourcegroup
          resourceGroupName: rg-iac101-demo
          template: "./IaC-101/main.bicep"
          # JSON dosyasını ve Secret'tan gelen şifreyi birleştiriyoruz
          parameters: "./IaC-101/demo.parameters.json adminPassword=${{ secrets.ADMIN_PASSWORD }}"